version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: tg-moderator-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tgmoderator
      POSTGRES_PASSWORD: tgmoderator
      POSTGRES_DB: tgmoderator
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tg-moderator-network

volumes:
  postgres_data:

networks:
  tg-moderator-network:
    driver: bridge
