bots:
  - id: "main_moderator"
    name: "Main Chat Moderator"
    # Автоматически ищет TELEGRAM_BOT_TOKEN_MAIN_MODERATOR
    chats:
      - chat_id: -1001234567890
        name: "Main Community"
        rules: ["spam", "hate_speech", "advertising"]
        warnings_before_ban: 3
        auto_delete_violations: true
      - chat_id: -1001234567891
        name: "Support Chat"
        rules: ["spam", "hate_speech"]
        warnings_before_ban: 2
        auto_delete_violations: false

  - id: "gaming_moderator"
    name: "Gaming Community Moderator"
    # Автоматически ищет TELEGRAM_BOT_TOKEN_GAMING_MODERATOR
    chats:
      - chat_id: -1001234567892
        name: "Gaming Chat"
        rules: ["spam", "hate_speech", "gaming_violations"]
        warnings_before_ban: 2
        auto_delete_violations: true
