rules:
  spam:
    name: "Спам и реклама"
    description: "Запрещены повторяющиеся сообщения, реклама без разрешения"
    ai_prompt: |
      Определи, является ли сообщение спамом или нежелательной рекламой.
      Критерии: повторяющиеся сообщения, коммерческая реклама без разрешения,
      массовые рассылки, флуд.
    severity: "medium"

  hate_speech:
    name: "Ненавистнические высказывания"
    description: "Запрещены оскорбления, дискриминация, призывы к насилию"
    ai_prompt: |
      Определи, содержит ли сообщение ненавистнические высказывания,
      оскорбления, дискриминацию или призывы к насилию.
    severity: "high"

  advertising:
    name: "Реклама"
    description: "Коммерческая реклама без разрешения администрации"
    ai_prompt: |
      Определи, содержит ли сообщение коммерческую рекламу товаров или услуг
      без явного разрешения администрации чата.
    severity: "medium"

  gaming_violations:
    name: "Нарушения в игровых чатах"
    description: "Спам в игровых командах, оскорбления игроков"
    ai_prompt: |
      Определи нарушения, специфичные для игровых чатов:
      спам в командах, оскорбления игроков, раскрытие личной информации.
    severity: "medium"
